service:
  name: glip-announcement-chatbot
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 256
  environment: ${file(./.env.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
package:
  exclude:
    - ./**
    - '!lambda.js'
    - '!app.js'
    - '!crontab.js'
    - '!node_modules/**'
  excludeDevDependencies: true
functions:
  app:
    handler: lambda.app
    timeout: 300
  proxy:
    handler: lambda.proxy
    events:
      - http: 'ANY {proxy+}'
  maintain:
    handler: lambda.maintain
    events:
      - schedule: rate(1 day)
  sendEmail:
    handler: lambda.sendEmail
    events:
      - schedule: rate(1 minute)
